name: First Workflow

on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo my string
              run: echo "Hello World"
            - name: Multiline Command
              run:  |
                uname -a
                env
                pwd
                whoami
                ip addr
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers
    dependant-job:
        runs-on: windows-latest
        needs: [run-shell-commands]
        steps:
            - name: echo strings from windows
              run: Write-Output "Windows String"
            - name: Error Step
              run: doesnotexists